version: '3.7'

services:

  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'

    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wp-network

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wp-network
    # Install Vim and Ping
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y vim iputils-ping &&
        docker-entrypoint.sh apache2-foreground
        && docker-php-ext-install bcmath
      "
  
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my-secret-pw
    networks:
      - wp-network

networks:
  wp-network:

volumes:
  db_data: